### Status
GET http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlvbmF4NzMiLCJpYXQiOjE3MDMwMTk1MTMsImV4cCI6MTcwMzAyMDQxM30.2odd-kteJ6o3MZeTiTICC01gKrR7FEZ47gnpVdUf-g8
